#!/usr/bin/env ruby

lib_dir = File.expand_path("../../lib", __FILE__)
$LOAD_PATH.unshift(lib_dir) unless $LOAD_PATH.include?(lib_dir)

require 'audio_book_creator'
require 'audio_book_creator/cli'

AudioBookCreator::Cli.new.parse(ARGV).run
